### PR TITLE
Change for placement of parts into batches for printing

### PR DESCRIPTION
**Pull request by icaven**
I wanted to see what it would cost to print the design using the Shapeways printing service, but to reduce the labour costs when printing in PLA, I needed to change the design to place the parts into separate batches, where the parts are connected by thin wires (the smallest supported by Shapeways) so that each batch is considered to be a single object. I have created a README to document these changes.

I changed other areas of the design file as well:  I use common modules to construct similar aspects of several parts, modified the shape of the gear teeth to the involute form, rounded the corners of the mounts, and changed the location of the filter wheel.

I haven't printed the revised design yet, but I would appreciate your thoughts on these changes.

### CODE REVIEW

**Comment by amchagas** [comment]
Hi @icaven,
thanks for putting some time an contributing to our project! Really appreciate it. 
I like the idea behind your implementation very much. However, I spotted some minor issues, that I think once corrected, could make this addition very valuable. In the end this might be something I'm doing wrong with the Flags here, forgive me if that is the case.
I'm collating the part of the code I played around with below, maybe that makes it easier to check if I'm doing something wrong

-When I render this code, although it seems that there are just a few pieces and it should be possible to arrange them, some still overlap 

- I tried playing around with the printbed size, but changing those numbers doesn't seem to change anything?

-Some of the parts with rounded corners have walls that might be too thin. Are you using minkowski for the rounding?

Thanks again!


´`/////////////////////////////////////////////////////////////////////////////////
/// FlyPi v0.97; 2015 05 27 ///
/// Collaboration Tom Baden, Lucia Prieto Godino and Andre Maia Chagas
/// 3D model by Tom Baden (thingyverse ID: tbaden) ///
/// thomas.baden@uni-tuebingen.de ///
/// tombaden.wordpress.com ///
/// Modified FlyPi_v29 by Ian Cavén 2017-10-24 for selectable assembly layout and other improvements 
/////////////////////////////////////////////////////////////////////////////////
//// SWITCHES //////////
PartA = 	0; // Base
PartA1 =	0; // Base clamps
PartA2 = 	0; // Feet
PartB =     0; // Wall
PartB3 =	1; // PCB mount

// Only the next two lines need to be set to control whether and which of the camera mounts are shown
show_camera_mount = 1;  
use_servo_focus = false;     // Set to true for PartC1 otherwise false for PartC
PartC = 	show_camera_mount && !use_servo_focus ? 1 : 0; // Cam Mount
PartC1 = 	show_camera_mount && use_servo_focus ? 1 : 0; // Cam Mount Servo - only use PartC or PartC1

PartC2_1 = 	1; // Cam Mount Cogwheel 1 - will only be made if use_servo_focus is true
PartC2_2 = 	1; // Cam Mount Cogwheel 2 - will only be made if use_servo_focus is true
PartD = 	1; // High Power LED mount
PartE =     1; // angled mounting stick
PartF1 = 	1; // straight mounting stick, long
PartF2 = 	1; // straight mounting stick, short
PartF3 = 	1; // straight mounting stick, long 90°
PartG = 	1; // thumbscrew & manipulator links
PartH = 	0; // AdaFruit 8x8 LED Matrix mount
PartI = 	1; // Adafruit 12 LED Ring mount
PartJ1 = 	0; // Mini Petri dish mount
PartJ2 = 	0; // Midi Petri dish mount
PartK = 	0; // Diffusor mount
PartL1 = 	0; // microscope slide chamber small
PartL2= 	0; // microscope slide chamber big
PartM = 	0; // Fluorescence Excitation light mount
PartN = 	0; // Fluorescence Exitaton tube plug
PartO = 	0; // Fluorescence Emission mount and wheel

/////////////////////////////////////////////////////////////////////////////////
///// KEY VARIABLES ////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////

// Set the assembly_location variable to one of the following two values to move the parts 
// to their location in the exploded view or their location when printing all parts
EXPLODED_VIEW = 1;
PRINTABLE_LAYOUT = 1;
assembly_location = EXPLODED_VIEW;
max_print_bounds = [500, 500, 500];  // X, Y, Z: the maximum bounding box supported by the printer
printing_batch_number = 2;  // Either 0, 1 or 2
connect_parts = (assembly_location == PRINTABLE_LAYOUT);   // Connect parts with bridges when printing a batch as a single part

// Make a layout guide for the maximum print bounding box
CHECKING_LAYOUT = false;
if (CHECKING_LAYOUT && assembly_location == PRINTABLE_LAYOUT)
{
    difference() {
        cube([max_print_bounds[0]+1, max_print_bounds[1]+1, 1], center=true); 
        cube([max_print_bounds[0], max_print_bounds[1], 1], center=true);
    }
}

sep = 30; // How far apart do pieces "float" in the model
MINIMUM_PRINT_LAYOUT_SEPARATION = 5;       // Minimum distance between parts for the print layout
MINIMUM_WIRE_SIZE = 2;  // Depends on the printer and the material
Walls = 5; // Global thickness of all walls
Tol = 0.2; // Global gap between all parts that need to slide
corner_radius = 4; // Round corner radius

´´

**Comment by icaven** [comment]
Hi Andre,

In the code above, the `assembly_location` variable is set to `EXPLODED_VIEW`, but in order to see how the parts can be printed together, it must be set to `PRINTABLE_LAYOUT`.

Also, in order to see the change in the print bed size, you will need to set `CHECKING_LAYOUT` to `true`.  Then, when you render the parts with 

> `assembly_location = PRINTABLE_LAYOUT;` 


you will see a thin border around the print area (only for the X-Y bounding rectangle - I chose to not show the full cube with the Z height, since that would make the placement of parts less clear).

The new print area won't be automatically used though;  the placement of parts is a manual (and tedious) process.  In addition to the placement of the parts, a choice needs to be made about which parts are to be included a batch.  I tried to select parts that appear to used together.

Yes, I use `minkowski` for the rounding in the module called Mount, on line 392.  Since the `minkowski` operation makes an object larger, I subtract the corner radius value from the X and Y dimensions, knowing that the object will be increased by that much again by `minkowski`.  Unless I made an error in the code, the Wall thickness should be preserved after the rounding.

I have found that, when using the OpenSCAD "Preview" menu command, the rendered part doesn't always look right.  You must use the (more time consuming) "Render" menu command to see the accurately rendered parts.

Ian.

**Comment by amchagas** [comment]
Hi Ian,

thanks for the explanations!
I forgot to write, but all of the usage I made was rendering the code. I think the main problem came from me not knowing what flags/things to change and how. 

Things look much better now. There is only a minor issue with some of the parts looking a bit off. (I'm so sorry if this is my inability to use this code!) but when I render  everything using "printing_batch_number = 1" two parts look strange (they are on one of the edges of the plate) and when in "printing_batch_number=0" the part that is placed inside the elevating feet also looks different. On exploded view, one can see this in the camera holder. 

Sorry to be bugging, this is a great addition to the repo, I just want to make sure other people will have no problem using it!

**Comment by icaven** [comment]
In `printing_batch_number = 0`, the camera holder has been placed inside the elevating feet  when rendering the printing layout just to make use of the empty space in there, to reduce the size of the printing area.  If  `use_servo_focus == true` then the gears would also appear inside the elevating feet part.

In `printing_batch_number = 1`, is it the manipulator links and thumbscrew that look strange to you?   They are connected by thin "wires" that are meant to be cut off after printing.  In the printing layout, all of the parts are connected by these "wires" to reduce the part count (Shapeways charges a fee for each part, so by connecting these pieces the total cost is greatly reduced).  Although I try to only show a wire when both of it's connected parts are switched in, it is possible that a wire is inadvertently shown even when only one of the parts is there (I haven't tried all of the combinations of switching parts in since I was thinking of the use case where most of the parts are to be printed at the same time).

I should also mention that I had to make some small adjustments to some of the parts where the automated Shapeways checks showed thin walls.  Those changes might lead to compatibility issues with parts printed from your previous version (I think that this would mostly affect the fit of the pillar sticks).

**Comment by amchagas** [comment]
> In printing_batch_number = 0, the camera holder has been placed inside the elevating feet when rendering the printing layout just to make use of the empty space in there, to reduce the size of the printing area. If use_servo_focus == true then the gears would also appear inside the elevating feet part.

What looks strange is not the placement of the part. The same camera holder in exploded view also looks strange. Here is a screenshot (https://www.dropbox.com/s/dmx3setlgdv9k99/cameraholder.png?dl=0) see how there is a wall missing in the back of the holder. Something similar is happening for the other parts I mentioned.

**Comment by icaven** [comment]
Yes, I see the problem now; thanks for pointing it out.  To correct it, I will change the `OPTICAL_AXIS_OFFSET_X` variable to set the offset amount to be the same as in the original design.  However, the placement of the parts need to be adjusted afterwards (since the mounts are larger), so I will do that before checking in the revision.

**Comment by icaven** [comment]
Hi. I have made the corrections, so please take a look when you can.

**Comment by amchagas** [comment]
Hi @icaven , it took me a while, but I finally managed to see your last update and merge it to the repo. 
It looks good. I'll just rename it to version 30, so that we can keep track of each version.
Thanks again for your input!!

**Comment by amchagas** [comment]
Hi @icaven, I hope your developments with the FlyPi are going well. I wanted to let you know that most of the development has moved over to https://github.com/prometheus-science/Flypi, so that we keep this repo as close as possible to the publication that came out describing it. 
Also, I created a new version of the 3d files, where each part is in a different file, and they can be imported, so that it is easier to create different plates for printing and so on. They can be found in: https://github.com/prometheus-science/Flypi/tree/master/3D_print_files/not_tested_yet/library

Hope this is useful!

**Comment by icaven** [comment]
Thanks for letting me know.  The reorganization of the parts into separate files make the design more readable.

**Pull request merged**
